image: alpine/edge
secrets:
  - b46c8b8f-4a58-4915-a134-be13d1e75015
environment:
  GH_USER: debarchito
  REPO: .bootstrap
tasks:
  - push-to-github: |
      cd ~/"${REPO}"
      git config --global credential.helper store
      git push --mirror "https://github.com/${GH_USER}/${REPO}"
