[context.nixos]
includes = ["modules/hosts/dell-laptop/_generated/hardware-configuration.nix"]
stubs = ["@nixos"]

[context.home-manager]
includes = [
  "modules/determinate.nix",
  "modules/features/browsers.nix",
  "modules/features/common.nix",
  "modules/features/desktop.nix",
  "modules/features/media.nix",
  "modules/features/packaging.nix",
  "modules/flake-file.nix",
  "modules/flake-parts.nix",
  "modules/home-manager.nix",
  "modules/import-tree.nix",
  "modules/nixpkgs.nix",
  "modules/packages/starship-jj.nix",
  "modules/packages/waydroid-script.nix",
  "modules/treefmt-nix.nix",
  "modules/users/debarchito.nix",
]
stubs = ["@home-manager"]

[stubs.generate]
nixpkgs = { expr = "(builtins.getFlake (toString ./.)).inputs.nixpkgs" }
home-manager = { expr = "(builtins.getFlake (toString ./.)).inputs.home-manager" }

[project]
includes = [
  "flake.nix",
  "modules/_templates/**/flake.nix",
  "modules/apps/impure-setup.nix",
  "modules/determinate.nix",
  "modules/features/**/*.nix",
  "modules/flake-file.nix",
  "modules/flake-parts.nix",
  "modules/home-manager.nix",
  "modules/hosts/dell-laptop/_generated/hardware-configuration.nix",
  "modules/hosts/dell-laptop/configuration.nix",
  "modules/hosts/dell-laptop/hardware.nix",
  "modules/import-tree.nix",
  "modules/nixpkgs.nix",
  "modules/overrides/debarchito.nix",
  "modules/packages/**/*.nix",
  "modules/templates.nix",
  "modules/treefmt-nix.nix",
  "modules/users/debarchito.nix",
]
excludes = ["result", ".direnv"]
