services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    hostname: debarchito_L
    ports:
      - "8384:8384"
      - "22000:22000/tcp"
      - "22000:22000/udp"
      - "21027:21027/udp"
    volumes:
      - /home/debarchito/.var/syncthing:/var/syncthing
    restart: unless-stopped
