[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]

[language-server.basedpyright.config]
python.analysis.venvPath = "."
python.analysis.venv = ".venv"
python.analysis.diagnosticMode = "workspace"
python.analysis.typeCheckingMode = "standard"

[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "python"
language-servers = ["basedpyright", "ruff"]
auto-format = true
formatter = { command = "ruff", args = ["format", "-"] }
